title: Kanagawa
logo: /assets/water-wave_1f30a.png
description: The source for Florida's Local Political Data and Reports
theme: jekyll-theme-minimal
google_analytics: UA-221463010-1
favicon: /assets/favicon.ico
