title: Kanagawa
logo: /assets/water-wave_1f30a.png
description: The source for Florida's Local Political Data and Reports
# theme: jekyll-theme-minimal
google_analytics: UA-221463010-1
favicon: /_includes/favicon.ico

remote_theme: pages-themes/dinky@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
